### ISSUE TITLE
Constants in lib/ cause "already initialized constant" warning

### ISSUE THREAD

**Issue by moll** [guard/guard-nanoc#11]
I've got a few files and filters in `lib/` that make use of constants (inside modules). Unfortunately, the more constants I use, the more warnings each compilation cycle prints. That's starting to get annoying as it hides useful information in a sea of irrelevance. (Aldous Huxley anyone?)

What's your take on getting Guard-Nanoc to reload code without such warnings?

**Comment by ddfreyne** [comment]
Closing this issue as it appears it has been resolved!

**Comment by moll** [comment]
Yay!
