### ISSUE TITLE
Require default bundle

### ISSUE THREAD

**Issue by ddfreyne** [guard/guard-nanoc#17]
Unlike _bin/nanoc_, guard-nanoc does not execute `Bundler.require(:default)` which means filters have to be required individually.

See nanoc/nanoc#494.

**Comment by ddfreyne** [comment]
With nanoc 4 coming up (which does not load the Gemfile), this might become a non-issue.

**Comment by mpapis** [comment]
with rubygems this is not an issue as gems are loaded automatically when `RUBYGEMS_GEMDEPS=-` is set
