### ISSUE TITLE
Could not load 'guard/nanoc' or '~/.guard/templates/nanoc' or find class Guard::Nanoc

### ISSUE THREAD

**Issue by LimeBlast** [guard/guard-nanoc#19]
I'm trying to use guard-nanoc with my project, but I can't get it to work.

Gemfile
```ruby
source 'https://rubygems.org'

gem 'nanoc'
gem 'adsf'
gem 'guard'
gem 'guard-nanoc'
```

After doing `bundle install` I try `bundle exec guard init nanoc` and get the following error:

```
16:23:36 - ERROR - Could not load 'guard/nanoc' or '~/.guard/templates/nanoc' or find class Guard::Nanoc
16:23:36 - ERROR - Error is: No such file or directory @ rb_sysopen - /home/daniel/.guard/templates/nanoc
```

**Comment by ddfreyne** [comment]
That’s quite odd—can you try uninstalling guard and nanoc (`gem uninstall`) and re-running `bundle install`?

**Comment by LimeBlast** [comment]
That seems to have fixed it, thank you.
