### ISSUE TITLE
guard-nanoc is slower than old nanoc autocompile

### ISSUE THREAD

**Issue by RubenVerborgh** [guard/guard-nanoc#23]
I recently upgraded to Nanoc 4, and started using guard-nanoc. However, the time it takes guard-nanoc to find a change and recompile the relevant documents seems longer than what nanoc autocompile previously did for me.

I think this falls apart in two challenges:

0. speeding up nanoc compilation in general (especially when very few things have actually changed)
0. caching more things in memory with guard-nanoc

Regarding the first point, I have some ideas (that I should perhaps post in the nanoc issue tracker).
Regarding the second point, I wonder to what extent guard-nanoc itself can be optimized to behave more like nanoc autocompile did?

My previous workflow was to keep `nanoc autocompile` running, make a change, then watch the browser (which would autoreload as I saved a file). Unfortunately, I cannot do this anymore with the latest Nanoc, as reloading is just too slow.

**Comment by RubenVerborgh** [comment]
Made performance issues nanoc/nanoc#789 and nanoc/nanoc#790.

**Comment by ddfreyne** [comment]
@RubenVerborgh Is this still an issue as of the current `release-4.2.x` branch?

**Comment by RubenVerborgh** [comment]
I will verify this week and let you know!

**Comment by RubenVerborgh** [comment]
It seems ok!
