### ISSUE TITLE
Server doesn't always terminate when guard exists

### ISSUE THREAD

**Issue by RubenVerborgh** [guard/guard-nanoc#27]
It often happens to me (OS X) that the HTTP server doesn't terminate when I stop guard, even though:

```
11:27:50 - INFO - Stopping process server
11:27:50 - INFO - Stopped process server

11:27:50 - INFO - Bye bye...
```

**Comment by ddfreyne** [comment]
guard-nanoc doesn’t run a HTTP server. Maybe you have `nanoc view` or `adsf` running somewhere?

**Comment by RubenVerborgh** [comment]
Ah woops, my `Guardfile` indeed has

```
guard :process, name: 'server', command: 'bundle exec serve' do
  watch 'Gemfile.lock'
end
```

Must have picked this up from somewhere.

**Comment by RubenVerborgh** [comment]
`guard -i` solved this BTW
