### ISSUE TITLE
"Compilation succeeded" notification displaying constantly after a change has happened 

### ISSUE THREAD

**Issue by iamuros** [guard/guard-nanoc#29]
After starting the guard and nanoc view, with any change the guard compiles and then keeps updating me with the "Compilation succeeded" notification.

I'm using Ubuntu 14.04 with: 
  Ruby 2.3.1p112 (RVM 1.27.0) 
  Nanoc 4.2.4 
  Guard version 2.14.0 
  Bundler version 1.12.5 

**Gemfile:**
source "https://rubygems.org"

LANG="en_US.UTF-8"
LC_ALL="en_US.UTF-8"

gem 'adsf'
gem 'builder'
gem 'kramdown'
gem 'sass'
gem 'mime-types'
gem 'compass'
gem 'nokogiri'
gem 'coderay'
gem 'haml'
gem 'json'
gem 'rainpress'
gem 'jsmin'
gem 'bootstrap-sass'
gem 'font-awesome-sass'
gem 'htmlcompressor'
gem 'nanoc'             # Nanoc 4
gem 'nanoc-external',   # :external filter
    :git => 'git://github.com/nanoc/nanoc-external.git',
    :branch => 'nanoc4'
gem 'guard-nanoc'
gem 'wdm', '>= 0.1.0' if Gem.win_platform?

**Guardfile:**
guard 'nanoc' do
  watch('nanoc.yaml') # Change this to config.yaml if you use the old config file name
  watch('Rules')
  watch(%r{^(content|layouts|lib)/.*$})
end

**Comment by ddfreyne** [comment]
This is intentional. This happens because without it, you’d not know when the recompilation is finished.

I’m assuming that you’re using `notify-send`, based off the fact that you’re on Ubuntu. Have you looked at customising the notification server to filter out notifications you’re not interested in?

**Comment by ddfreyne** [comment]
I will close this for now, with the suggested resolution action being to look into options for configuring `notify-send` to hide “success” notifications.
