### ISSUE TITLE
Running guard-nanoc on Docker

### ISSUE THREAD

**Issue by Brodan** [guard/guard-nanoc#30]
Is there a way to make guard-nanoc Docker friendly?

My Docker/guard knowledge is limited, but I understand that a Docker container can only run one CMD, so it seems as though guard-nanoc can't be run in a single container since you need to run `$ bundle exec guard` AND `$ bundle exec nanoc view`.

Am I correct in thinking this? Is there a way to circumvent this/run both of these services as one?
I don't want to have to run two containers for this to work.

**Comment by Brodan** [comment]
I'm just now noticing that #28 is exactly what I was looking for. Is there an ETA on that?

**Comment by ddfreyne** [comment]
The PR #28 is unblocked and merged, and will be released in a bit.

**Comment by ddfreyne** [comment]
This is now available in Nanoc 4.3 and guard-nanoc 2.1!
